### ISSUE TITLE
Errors about `--port`

### ISSUE THREAD

**Issue by scillidan** [GradientSurfer/Draw2Img#2]
Dud, I can host it from `localhost:8080` but cannot set the special port.

![image](https://github.com/GradientSurfer/Draw2Img/assets/19889610/40327783-8e1e-4e05-907f-c17c48ec0386)

![image](https://github.com/GradientSurfer/Draw2Img/assets/19889610/910b3a03-07b7-468e-bf5a-4cfee7a768d7)

![image](https://github.com/GradientSurfer/Draw2Img/assets/19889610/43266e41-99ce-4e9f-b05a-b7be88f93125)

![image](https://github.com/GradientSurfer/Draw2Img/assets/19889610/b06e46b4-ed26-4edb-8626-f8c7420af4d4)

**Comment by GradientSurfer** [comment]
Thank you for the detailed report @scillidan, sorry for the trouble! I forgot the Websocket port was hard-coded in the UI, this is fixed now.

**Comment by scillidan** [comment]
Cheers :)
