### ISSUE TITLE
  error: subprocess-exited-with-error

### ISSUE THREAD

**Issue by yinyangfs** [GradientSurfer/Draw2Img#4]
enviroment win10 x64  python-3.12.1-amd64.exe

after pip install . all ok  but at the end of progression show error such as follows:

Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'error'
  error: subprocess-exited-with-error

  Preparing metadata (pyproject.toml) did not run successfully.
  exit code: 1

  [6 lines of output]

  Cargo, the Rust package manager, is not installed or is not on PATH.
  This package requires Rust and Cargo to compile extensions. Install it through
  the system's package manager or via https://rustup.rs/

  Checking for Rust toolchain....
  [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

Encountered error while generating package metadata.

See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

[notice] A new release of pip is available: 23.2.1 -> 23.3.2
[notice] To update, run: python.exe -m pip install --upgrade pip

-----------------------------------------------------------

then go on next step the console show :
$ python draw2img/main.py
Traceback (most recent call last):
  File "C:\Users\yangyanghub\Desktop\draw2\Draw2Img\draw2img\main.py", line 9, in <module>
    import fire
ModuleNotFoundError: No module named 'fire'

**Comment by GradientSurfer** [comment]
Hi @yinyangfs thanks for the report, could you try Python 3.10 or 3.11 instead? I don't think Python 3.12 is supported yet by the dependencies used in this project.

Edit: I was able to reproduce this error on win10 x64 python-3.12. I confirmed that downgrading to Python 3.11 fixes the issue.

You can use a specific version of Python via conda/miniconda like this:

```bash
conda create -n "draw2img" python=3.11
conda activate draw2img
pip install .
```

**Comment by yinyangfs** [comment]
@GradientSurfer ty you quickly reply ! i will try  to use the minicoda and downgrading to python3.11 !
as soon as i tested i will  give you feedback!

**Comment by yinyangfs** [comment]
fixed  downgrading to python3.11 and work well ty
