### ISSUE TITLE
i can`t do it 

### ISSUE THREAD

**Issue by NazarCiho** [GradientSurfer/Draw2Img#7]
pip : The term 'pip' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that 
the path is correct and try again.
At line:1 char:1                  
+ pip install .
+ ~~~
    + CategoryInfo          : ObjectNotFound: (pip:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by GradientSurfer** [comment]
Hi @NazarCiho it seems you may be having trouble setting up a python environment on Windows. Unfortunately I won't be able to help with that but I recommend using [conda and following the getting started guide](https://conda.io/projects/conda/en/latest/user-guide/getting-started.html).
